version: '3.8'

services:

  notification-mysql:
    image: mysql:8.0
    container_name: notificationService_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notification_db
      MYSQL_USER: Mahmoud
      MYSQL_PASSWORD: 123456789
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "33064:3306"
    volumes:
      - notification_mysql_data:/var/lib/mysql

  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "8084:8080"
    depends_on:
       notification-mysql:
         condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notification-mysql:3306/notification_db
      SPRING_DATASOURCE_USERNAME: Mahmoud
      SPRING_DATASOURCE_PASSWORD: 123456789
    networks:
      - microservices-net  # Add network

volumes:
  notification_data:
networks:
  microservices-net:
    external: true