version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: taskService_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_db
      MYSQL_USER: Mahmoud
      MYSQL_PASSWORD: 123456789
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build: target
    container_name: taskService-database
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_db
      SPRING_DATASOURCE_USERNAME: Mahmoud
      SPRING_DATASOURCE_PASSWORD: 123456789

volumes:
  task_data: