version: "3.8"

services:

  # Eureka
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  # Auth Service
  auth-mysql:
    image: mysql:8
    container_name: auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "33061:3306"

  auth-service:
    build: ./AuthService
    container_name: auth-service
    depends_on:
      - auth-mysql
      - eureka-server

  # User Service
  user-mysql:
    image: mysql:8
    container_name: user-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "33062:3306"

  user-service:
    build: ./UserService
    container_name: user-service
    depends_on:
      - user-mysql
      - eureka-server

  # Task Service
  task-mysql:
    image: mysql:8
    container_name: task-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - "33063:3306"

  task-service:
    build: ./TaskService
    container_name: task-service
    depends_on:
      - task-mysql
      - eureka-server

  # Notification Service
  notification-mysql:
    image: mysql:8
    container_name: notification-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_db
    ports:
      - "33064:3306"

  notification-service:
    build: ./NotificationService
    container_name: notification-service
    depends_on:
      - notification-mysql
      - eureka-server
